colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = false
enableStructuredBreadcrumbs = true

disableImageOptimization = false
disableTextInHeader = false

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  homepageImage = "img/hero.jpg"
  showRecent = true
  showRecentItems = 9
  showMoreLink = true
  showMoreLinkDest = "/categories/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "big"
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["twitter", "facebook", "reddit", "linkedin", "whatsapp", "email"]

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  orderByWeight = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = true
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
